version: '2'
services:
  db:
    image: postgres

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=settings
    command: /bin/bash -c "cd /code/;
      pip install -r requirements.txt;
      yes yes | ./manage.py collectstatic;
      yes yes | ./manage.py migrate;
      uwsgi --http :8000 --module 'django.core.wsgi:get_wsgi_application()'  --processes 4 --threads 2 --py-autoreload 1 --static-map /static=/code/static"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: client
    volumes:
      - ./client:/client
      - ./static:/static
    command: /bin/bash -c "cd /client;
      npm install -g gulp;
      npm install;
      gulp watch"
